name: pomodoro_app

description: Focus timer MVP

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  just_audio: ^0.9.38
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/ButtonBackground.png
    - assets/PomodoroBtnBackground.png
    - assets/ButtonBackgroundDarkBlue.png
    - assets/ButtonBackgroundGrey.png
    - assets/ButtonBackgroundDarkGrey.png
    - assets/AppBackground.png
    - assets/AppBackgroundDark.png
    - assets/sounds/rain.mp3
    - assets/sounds/ocean.mp3
    - assets/sounds/forest.mp3
    - assets/sounds/fire.mp3
    - assets/sounds/white.mp3
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VF.ttf
